// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectCalculationService.DataAccess;

#nullable disable

namespace ProjectCalculationService.DataAccess.Migrations;

[DbContext(typeof(ProjectCalculationDbContext))]
[Migration("202605170001_AddProjectOptimizations")]
public partial class AddProjectOptimizations
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.22")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ProjectCalculationService.Application.Models.Project", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<Guid>("OwnerUserId")
                .HasColumnType("uuid");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("OwnerUserId");

            b.ToTable("projects");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.Optimizations.ProjectOptimization", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("CommunicationType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("CreatedByUserId")
                .HasColumnType("uuid");

            b.Property<int>("EndX")
                .HasColumnType("integer");

            b.Property<int>("EndY")
                .HasColumnType("integer");

            b.Property<Guid>("ProjectId")
                .HasColumnType("uuid");

            b.Property<string>("ResultJson")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<string>("SelectedVariant")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<int>("StartX")
                .HasColumnType("integer");

            b.Property<int>("StartY")
                .HasColumnType("integer");

            b.Property<string>("TemplateId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.HasKey("Id");

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "CreatedAt");

            b.ToTable("project_optimizations");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.ProjectStepAnswer", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("AnswerType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<Guid>("ProjectId")
                .HasColumnType("uuid");

            b.Property<string>("SelectedOptionCode")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<string>("StepCode")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid?>("UpdatedByUserId")
                .HasColumnType("uuid");

            b.Property<string>("ValueJson")
                .HasColumnType("jsonb");

            b.HasKey("Id");

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "StepCode")
                .IsUnique();

            b.ToTable("project_step_answers");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.SharedProject", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean");

            b.Property<Guid>("ProjectId")
                .HasColumnType("uuid");

            b.Property<DateTime>("SharedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Code")
                .IsUnique();

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "IsActive");

            b.ToTable("shared_projects");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.SharedProjectViewer", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean");

            b.Property<Guid>("ShareId")
                .HasColumnType("uuid");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ShareId");

            b.HasIndex("UserId", "IsActive");

            b.HasIndex("UserId", "ShareId")
                .IsUnique();

            b.ToTable("shared_project_viewers");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.ViewerComment", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid");

            b.Property<string>("CommentText")
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnType("character varying(4000)");

            b.Property<DateTime>("CommentDate")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)");

            b.Property<Guid>("ProjectId")
                .HasColumnType("uuid");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "CommentDate");

            b.ToTable("viewer_comments");
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.Optimizations.ProjectOptimization", b =>
        {
            b.HasOne("ProjectCalculationService.Application.Models.Project", null)
                .WithMany()
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.ProjectStepAnswer", b =>
        {
            b.HasOne("ProjectCalculationService.Application.Models.Project", null)
                .WithMany()
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.SharedProject", b =>
        {
            b.HasOne("ProjectCalculationService.Application.Models.Project", null)
                .WithMany()
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.SharedProjectViewer", b =>
        {
            b.HasOne("ProjectCalculationService.Application.Models.SharedProject", null)
                .WithMany()
                .HasForeignKey("ShareId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("ProjectCalculationService.Application.Models.ViewerComment", b =>
        {
            b.HasOne("ProjectCalculationService.Application.Models.Project", null)
                .WithMany()
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}

